# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Halide::Tools Halide::ImageIO Halide::RunGenMain Halide::Runtime Halide::retrain_cost_model Halide::featurization_to_sample Halide::get_host_target Halide::weightsdir_to_weightsfile)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Halide::Tools
add_library(Halide::Tools INTERFACE IMPORTED)

set_target_properties(Halide::Tools PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/share/Halide/tools"
)

# Create imported target Halide::ImageIO
add_library(Halide::ImageIO INTERFACE IMPORTED)

set_target_properties(Halide::ImageIO PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<NOT:\$<TARGET_EXISTS:PNG::PNG>>:HALIDE_NO_PNG>;\$<\$<NOT:\$<TARGET_EXISTS:JPEG::JPEG>>:HALIDE_NO_JPEG>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/share/Halide/tools"
  INTERFACE_LINK_LIBRARIES "\$<TARGET_NAME_IF_EXISTS:PNG::PNG>;\$<TARGET_NAME_IF_EXISTS:JPEG::JPEG>"
)

# Create imported target Halide::RunGenMain
add_library(Halide::RunGenMain INTERFACE IMPORTED)

set_target_properties(Halide::RunGenMain PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/share/Halide/tools"
  INTERFACE_LINK_LIBRARIES "Halide::Runtime;Halide::ImageIO;Threads::Threads"
  INTERFACE_SOURCES "${_IMPORT_PREFIX}/share/Halide/tools/RunGenMain.cpp"
)

# Create imported target Halide::Runtime
add_library(Halide::Runtime INTERFACE IMPORTED)

set_target_properties(Halide::Runtime PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Halide::retrain_cost_model
add_executable(Halide::retrain_cost_model IMPORTED)

# Create imported target Halide::featurization_to_sample
add_executable(Halide::featurization_to_sample IMPORTED)

# Create imported target Halide::get_host_target
add_executable(Halide::get_host_target IMPORTED)

# Create imported target Halide::weightsdir_to_weightsfile
add_executable(Halide::weightsdir_to_weightsfile IMPORTED)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/Halide-Interfaces-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
